from pathlib import Path
import hashlib
root=Path('.')
old={'index.html': 'ce79e9908e882569046c5d7e83fe1030a828ba984672d2f1815e7c67ea408899', 'service-worker.js': '5ed7756c32b45b9ca11d6cbeb3d1b3625185e4ed6b279c4dc98b66759ab38bc8', 'RELEASE.txt': 'a2c823c9f32901ac676f5392c5b7280dc6ce4e0c2a8c2789f1b414bee55f2bba', 'src/core/update-manager.js': '17fdca5adbf9912938fe77a65f6c11a3b17e7a30fd199b1ff7a434f8438b4381', 'src/core/database-diagnostics.js': '3d96a26328e9fd4524bacd3d034bc3345df5bb2e3817e61ce5535dbb2a55534b', 'src/ui/update-ui.js': '30353150d10313f6aff9349423bb2c6bcf38806618296f789109a4778d0a566f', 'src/ui/app.js': '27a466319f8767783d2921cfbef4c572318f0c69409a7cbbcb51145b17d5082e', 'src/ui/role-ux.js': '304547c6e33ce4ace4d1bb238c9e63138a95c1898ae1b9814adf673867cc9304', 'src/adapters/storage.js': 'ef043726c8c97a278f4da89dd621ab2045d7486ca47fed2cc414594f6ee7c148'}
new={'index.html': '93229d8d09558ebcb0744bf2622fee65f328baf13f485adefc539c0a019239d3', 'service-worker.js': '5c0c9bce7539731f98edf94eeef2bc2564067fdd0853f729dd0873bfb47e2e0c', 'RELEASE.txt': '582f8f7c6fc2b5c71a8178a469b1b4874d69c36a352e2a2c5c16f8ea64963614', 'src/core/update-manager.js': 'aadf93b505480ad89ec10462c19c5d6343060410c928d41031b98ba13f89dfde', 'src/core/database-diagnostics.js': '1bfc3975052f533662af93b1f1b4223c7cec43ec2b36ab4ec1ca58911f227913', 'src/ui/update-ui.js': '58ca2cd787bcd13aeea78b6a32cc5f9eae879e59c95cf961e9f7440001ecee8f', 'src/ui/app.js': '372f65d48734d252be1a61a8a738e7fd225407afc042a3523a3c5d90f292d6f0', 'src/ui/role-ux.js': 'a00d7e972c7e63c8d218f7d60cb40a0405471df9e8ae382c7ac9bcd9247e58d3', 'src/adapters/storage.js': '0b1f36de635a749d0633603ef27d53df94a7ce4d4caed5c8af428361557122db'}
for rel,want in old.items():
    got=hashlib.sha256((root/rel).read_bytes()).hexdigest()
    if got!=want: raise SystemExit(f'V0.19.14 base hash mismatch: {rel} {got} != {want}')

def rw(rel,a,b,count=1):
    p=root/rel;s=p.read_text(encoding='utf-8')
    if a not in s: raise SystemExit(f'pattern missing in {rel}: {a[:120]}')
    p.write_text(s.replace(a,b,count),encoding='utf-8')

rw('src/adapters/storage.js',"""    async getMany(keys){
      this.requireUnlock();if(!this.db)await this.init();const wanted=[...new Set(keys||[])];if(!wanted.length)return[];idbTraffic('get');const t=perf();
      const rows=await new Promise((resolve,reject)=>{const tx=this.db.transaction('encrypted_envelopes','readonly'),q=tx.objectStore('encrypted_envelopes').getAll();q.onsuccess=()=>resolve(q.result||[]);q.onerror=()=>reject(q.error);}),map=new Map(rows.map(r=>[r.key,r]));
      const values=await Promise.all(wanted.map(async key=>{const row=map.get(key);return row?this._decryptAny(key,row.envelope,{migrate:true}):undefined;}));this.cryptoStats.lastBatchReadMs=Math.round((perf()-t)*10)/10;return values;
    },""", """    async getMany(keys){
      this.requireUnlock();if(!this.db)await this.init();const wanted=[...new Set(keys||[])];if(!wanted.length)return[];idbTraffic('get');const t=perf();
      const tx=this.db.transaction('encrypted_envelopes','readonly'),st=tx.objectStore('encrypted_envelopes'),done=txDone(tx);
      const rows=await Promise.all(wanted.map(key=>new Promise((resolve,reject)=>{const q=st.get(key);q.onsuccess=()=>resolve(q.result);q.onerror=()=>reject(q.error);})));await done;
      const values=await Promise.all(rows.map((row,i)=>row?this._decryptAny(wanted[i],row.envelope,{migrate:true}):undefined));this.cryptoStats.lastBatchReadMs=Math.round((perf()-t)*10)/10;return values;
    },""")

rw('src/ui/app.js',"""async function persist(){try{traffic('idb');K.refreshWorkflowState?.();const syncSnap=K.sync?.snapshot?.()||{outbox:[],conflicts:[],meta:{status:'offline'}};const entries=[
['shifts',K.shifts],['standby',K.standby],['wishes',K.wishes],['workflow',K.workflow],['planVersions',K.planVersions],['acknowledgements',K.acknowledgements],['swapRequests',K.swapRequests],['peopleSnapshot',K.people],['auditLog',K.auditLog||[]],['syncOutbox',syncSnap.outbox],['syncConflicts',syncSnap.conflicts],['syncMeta',syncSnap.meta],
['personRules',K.personRules||{}],['absences',K.absences||[]],['replacementRequests',K.replacementRequests||[]],['memberUxData',K.memberUxData||{}],['actualShifts',K.actualShifts||[]],['breakConfig',K.breakConfig||{}],['actualImportBatches',K.actualImportBatches||[]],['actualCorrectionRequests',K.actualCorrectionRequests||[]],['actualWorkflow',K.actualWorkflow||{}],['actualPlanVersions',K.actualPlanVersions||[]],['actualConfig',K.actualConfig||{}],['documentLog',K.documentLog||[]],['deliveryLog',K.deliveryLog||[]],['notificationInbox',K.notificationInbox||[]],['notificationPreferences',K.notificationPreferences||{}],['pushSubscriptions',K.pushSubscriptions||{}],['eventConfig',K.eventConfig||{}],['daySettings',K.daySettings||{}],['demandMatrix',K.demandMatrix||{}],['daysRuntime',K.days.map(d=>({date:d.date,weather:d.weather,program:d.program,notes:d.notes||''}))],['planLocks',K.planLocks||{}],['integrationConfig',K.integrations?.snapshot?.()||K.integrationConfig||{}]
];await (K.storage.putMany?K.storage.putMany(entries):Promise.all(entries.map(([k,v])=>K.storage.put(k,v))));K.historyManager?.record?.('Gespeicherte Änderung');K.recovery?.scheduleCheckpoint?.('persist');updateUndoRedoUI();msg('✓ Änderung lokal verschlüsselt gespeichert.','success',undoAction);}catch(e){$('idbStatusLed').className='led led-status error';msg('✕ Lokales Speichern fehlgeschlagen: '+e.message,'error')}}
K.persistAll=persist;""", """const persistFingerprints=new Map();
function persistenceEntries(){const syncSnap=K.sync?.snapshot?.()||{outbox:[],conflicts:[],meta:{status:'offline'}};return [
['shifts',K.shifts],['standby',K.standby],['wishes',K.wishes],['workflow',K.workflow],['planVersions',K.planVersions],['acknowledgements',K.acknowledgements],['swapRequests',K.swapRequests],['peopleSnapshot',K.people],['auditLog',K.auditLog||[]],['syncOutbox',syncSnap.outbox],['syncConflicts',syncSnap.conflicts],['syncMeta',syncSnap.meta],
['personRules',K.personRules||{}],['absences',K.absences||[]],['replacementRequests',K.replacementRequests||[]],['memberUxData',K.memberUxData||{}],['actualShifts',K.actualShifts||[]],['breakConfig',K.breakConfig||{}],['actualImportBatches',K.actualImportBatches||[]],['actualCorrectionRequests',K.actualCorrectionRequests||[]],['actualWorkflow',K.actualWorkflow||{}],['actualPlanVersions',K.actualPlanVersions||[]],['actualConfig',K.actualConfig||{}],['documentLog',K.documentLog||[]],['deliveryLog',K.deliveryLog||[]],['notificationInbox',K.notificationInbox||[]],['notificationPreferences',K.notificationPreferences||{}],['pushSubscriptions',K.pushSubscriptions||{}],['eventConfig',K.eventConfig||{}],['daySettings',K.daySettings||{}],['demandMatrix',K.demandMatrix||{}],['daysRuntime',K.days.map(d=>({date:d.date,weather:d.weather,program:d.program,notes:d.notes||''}))],['planLocks',K.planLocks||{}],['integrationConfig',K.integrations?.snapshot?.()||K.integrationConfig||{}]
];}
function persistenceFingerprint(v){try{return JSON.stringify(v);}catch(_){return String(v);}}
function seedPersistFingerprints(){persistFingerprints.clear();for(const [k,v] of persistenceEntries())persistFingerprints.set(k,persistenceFingerprint(v));}
async function persist(){try{traffic('idb');K.refreshWorkflowState?.();const started=performance.now(),entries=persistenceEntries(),serialized=new Map(entries.map(([k,v])=>[k,persistenceFingerprint(v)])),changed=entries.filter(([k])=>persistFingerprints.get(k)!==serialized.get(k));if(changed.length){await (K.storage.putMany?K.storage.putMany(changed):Promise.all(changed.map(([k,v])=>K.storage.put(k,v))));for(const [k] of changed)persistFingerprints.set(k,serialized.get(k));}K.performanceMetrics.lastPersistMs=Math.round((performance.now()-started)*10)/10;K.performanceMetrics.lastPersistKeys=changed.length;K.historyManager?.record?.('Gespeicherte Änderung');K.recovery?.scheduleCheckpoint?.('persist');updateUndoRedoUI();msg(`✓ Änderung lokal verschlüsselt gespeichert${changed.length?` · ${changed.length} Bereich(e) · ${K.performanceMetrics.lastPersistMs} ms`:' · keine Datenänderung'}.`,'success',undoAction);}catch(e){$('idbStatusLed').className='led led-status error';msg('✕ Lokales Speichern fehlgeschlagen: '+e.message,'error')}}
K.persistAll=persist;""")

rw('src/ui/app.js',"(async function init(){\n  try{","(async function init(){\n  let startupPg=null;\n  try{")
rw('src/ui/app.js',"""    await K.storage.init();await K.memberAccess?.restorePublicConfig?.();const rememberAuth=await K.memberAccess?.rememberedHint?.();if(rememberAuth){await unlockSecureStore();await ensureFastLocalStore();const earlySession=await K.storage.get('supabaseSession');if(earlySession)K.supabaseConnection?.restoreSession?.(earlySession);let restored=null;try{restored=await K.memberAccess?.restore?.();}catch(_){restored=null}if(!restored)await K.roleUx?.ensureLogin?.();}else{await K.roleUx?.ensureLogin?.();await unlockSecureStore();await ensureFastLocalStore();}await K.memberAccess?.persistSessionIfNeeded?.();$('idbStatusLed').className='led led-status ok';
    const localLoadStarted=performance.now();const keys=""", """    await K.storage.init();await K.memberAccess?.restorePublicConfig?.();const rememberAuth=await K.memberAccess?.rememberedHint?.();if(rememberAuth){await unlockSecureStore();await ensureFastLocalStore();const earlySession=await K.storage.get('supabaseSession');if(earlySession)K.supabaseConnection?.restoreSession?.(earlySession);let restored=null;try{restored=await K.memberAccess?.restore?.();}catch(_){restored=null}if(!restored)await K.roleUx?.ensureLogin?.();}else{await K.roleUx?.ensureLogin?.();await unlockSecureStore();await ensureFastLocalStore();}startupPg=taskProgressOpen('KC-DP2 wird vorbereitet','Lokale Daten werden entschlüsselt und die Oberfläche vorbereitet.',4);startupPg.update({done:1,total:4,label:'Sicherer Geräteschlüssel ist bereit'});await K.memberAccess?.persistSessionIfNeeded?.();startupPg.update({done:2,total:4,label:'Anmeldung und Sitzung sind vorbereitet'});$('idbStatusLed').className='led led-status ok';
    const localLoadStarted=performance.now();const keys=""")
rw('src/ui/app.js',"const vals=K.storage.getMany?await K.storage.getMany(keys):await Promise.all(keys.map(k=>K.storage.get(k)));K.performanceMetrics.localLoadMs=Math.round((performance.now()-localLoadStarted)*10)/10;","const vals=K.storage.getMany?await K.storage.getMany(keys):await Promise.all(keys.map(k=>K.storage.get(k)));K.performanceMetrics.localLoadMs=Math.round((performance.now()-localLoadStarted)*10)/10;startupPg.update({done:3,total:4,label:`Lokale Daten geladen · ${K.performanceMetrics.localLoadMs} ms`});")
rw('src/ui/app.js','    K.refreshWorkflowState();syncLed();','    K.refreshWorkflowState();syncLed();seedPersistFingerprints();')
rw('src/ui/app.js',"render();K.roleUx?.afterDataLoaded?.();if(Number.isFinite(K.performanceMetrics.postAuthStartedAt))K.performanceMetrics.firstScreenMs=Math.round((performance.now()-K.performanceMetrics.postAuthStartedAt)*10)/10;","render();K.roleUx?.afterDataLoaded?.();if(Number.isFinite(K.performanceMetrics.postAuthStartedAt))K.performanceMetrics.firstScreenMs=Math.round((performance.now()-K.performanceMetrics.postAuthStartedAt)*10)/10;try{startupPg?.finish?.(`✓ KC-DP2 bereit · erster Bildschirm ${Number.isFinite(K.performanceMetrics.firstScreenMs)?K.performanceMetrics.firstScreenMs+' ms':'geladen'}`);}catch(_){}")
rw('src/ui/app.js',"<small>Batch-Lesen ${Number.isFinite(K.storage?.cryptoStats?.lastBatchReadMs)?K.storage.cryptoStats.lastBatchReadMs+' ms':'–'} · Batch-Schreiben ${Number.isFinite(K.storage?.cryptoStats?.lastBatchWriteMs)?K.storage.cryptoStats.lastBatchWriteMs+' ms':'–'} · PBKDF2 einmal/Sitzung ${Number.isFinite(K.storage?.cryptoStats?.keyDeriveMs)?K.storage.cryptoStats.keyDeriveMs+' ms':'–'}</small>","<small>Batch-Lesen ${Number.isFinite(K.storage?.cryptoStats?.lastBatchReadMs)?K.storage.cryptoStats.lastBatchReadMs+' ms':'–'} · Batch-Schreiben ${Number.isFinite(K.storage?.cryptoStats?.lastBatchWriteMs)?K.storage.cryptoStats.lastBatchWriteMs+' ms':'–'} · letzte Änderung ${Number.isFinite(K.performanceMetrics?.lastPersistMs)?K.performanceMetrics.lastPersistMs+' ms / '+(K.performanceMetrics.lastPersistKeys||0)+' Bereich(e)':'–'} · PBKDF2 einmal/Sitzung ${Number.isFinite(K.storage?.cryptoStats?.keyDeriveMs)?K.storage.cryptoStats.keyDeriveMs+' ms':'–'}</small>")

rw('src/ui/role-ux.js',""" $('uxLoginForm').onsubmit=async e=>{e.preventDefault();scrubBadAutofill();const mail=String($('uxEmail').value||'').trim();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(mail)){insertLoginError('Bitte geben Sie Ihre persönliche E-Mail-Adresse ein.');$('uxEmail').focus();return;}const b=e.submitter;b.disabled=true;b.textContent='Anmeldung läuft…';const authStarted=performance.now();try{await K.memberAccess.signInPassword({email:mail,password:$('uxPassword').value,remember:$('uxRemember').checked});K.performanceMetrics=K.performanceMetrics||{};K.performanceMetrics.authMs=Math.round((performance.now()-authStarted)*10)/10;finishLogin();}catch(err){loginScreen(err.message)}};""", """ $('uxLoginForm').onsubmit=async e=>{e.preventDefault();scrubBadAutofill();const mail=String($('uxEmail').value||'').trim();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(mail)){insertLoginError('Bitte geben Sie Ihre persönliche E-Mail-Adresse ein.');$('uxEmail').focus();return;}const b=e.submitter;b.disabled=true;b.textContent='Anmeldung läuft…';const authStarted=performance.now(),pg=K.taskProgress?.open?.('Anmeldung läuft','KC-DP2 prüft Ihre Supabase-Anmeldung und lädt die zugeordnete Rolle.',3);try{pg?.update?.({done:1,total:3,label:'Supabase-Anmeldung wird geprüft…'});await K.memberAccess.signInPassword({email:mail,password:$('uxPassword').value,remember:$('uxRemember').checked});pg?.update?.({done:2,total:3,label:'Mitglied und Rolle wurden bestätigt'});K.performanceMetrics=K.performanceMetrics||{};K.performanceMetrics.authMs=Math.round((performance.now()-authStarted)*10)/10;pg?.finish?.(`✓ Anmeldung bestätigt · ${K.performanceMetrics.authMs} ms`);finishLogin();}catch(err){pg?.close?.();loginScreen(err.message)}};""")

for a,b in [("active:true,version:'0.19.14'","active:true,version:'0.19.15'"),("||'0.19.14'","||'0.19.15'"),("K.roleUx={version:'0.19.14'","K.roleUx={version:'0.19.15'")]: rw('src/ui/role-ux.js',a,b)
for a,b in [("CURRENT_RELEASE='0.19.14'","CURRENT_RELEASE='0.19.15'"),("service-worker.js?v=0.19.14-engine","service-worker.js?v=0.19.15-engine"),("version:'0.19.14'","version:'0.19.15'")]: rw('src/core/update-manager.js',a,b,2 if a.startswith('service-worker') else 1)
rw('src/ui/update-ui.js',"version:'0.19.14'","version:'0.19.15'")
rw('src/core/database-diagnostics.js',"version:'0.19.14'","version:'0.19.15'")
for a,b in [('src/core/database-diagnostics.js?v=0.17.10','src/core/database-diagnostics.js?v=0.19.15'),('src/adapters/storage.js?v=0.17.10','src/adapters/storage.js?v=0.19.15'),('src/ui/role-ux.js?v=0.19.14','src/ui/role-ux.js?v=0.19.15'),('src/core/update-manager.js?v=0.19.14','src/core/update-manager.js?v=0.19.15'),('src/ui/update-ui.js?v=0.19.14','src/ui/update-ui.js?v=0.19.15'),('src/ui/app.js?v=0.19.14','src/ui/app.js?v=0.19.15')]: rw('index.html',a,b)
for a,b in [('./src/core/database-diagnostics.js?v=0.17.10','./src/core/database-diagnostics.js?v=0.19.15'),('./src/adapters/storage.js?v=0.17.10','./src/adapters/storage.js?v=0.19.15'),('./src/ui/role-ux.js?v=0.19.14','./src/ui/role-ux.js?v=0.19.15'),('./src/core/update-manager.js?v=0.19.14','./src/core/update-manager.js?v=0.19.15'),('./src/ui/update-ui.js?v=0.19.14','./src/ui/update-ui.js?v=0.19.15'),('./src/ui/app.js?v=0.19.14','./src/ui/app.js?v=0.19.15')]: rw('service-worker.js',a,b)
rw('src/ui/app.js','DB-Diagnose V0.19.14','DB-Diagnose V0.19.15')
rw('src/ui/app.js','KC DP V0.19.14 – eigenes Supabase-Dienstplanprojekt und Diagnose bereit.','KC DP V0.19.15 – Performance-Optimierung und Diagnose bereit.')
(root/'RELEASE.txt').write_text('KC-DP2 0.19.15\n',encoding='utf-8')

for rel,want in new.items():
    got=hashlib.sha256((root/rel).read_bytes()).hexdigest()
    if got!=want: raise SystemExit(f'V0.19.15 result hash mismatch: {rel} {got} != {want}')
print('KC-DP2 V0.19.15 performance patch OK')
