import { createClient } from 'npm:@supabase/supabase-js@2';
import webpush from 'npm:web-push@3.6.7';
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'content-type,apikey,authorization','Access-Control-Allow-Methods':'GET,POST,OPTIONS'};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,'Content-Type':'application/json','Cache-Control':'no-store'}});
const sha256=async(v:string)=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v)))).map(x=>x.toString(16).padStart(2,'0')).join('');
const rank:Record<string,number>={invited:0,opened:1,installed:2,push_enabled:3,test_received:4,completed:5,revoked:99};
Deno.serve(async(req)=>{
 if(req.method==='OPTIONS')return new Response('ok',{headers:cors});
 const admin=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!);let body:any={};if(req.method==='POST'){try{body=await req.json()}catch{return json({error:'Ungültige Anfrage'},400)}}
 const token=String(body.token||new URL(req.url).searchParams.get('token')||'');if(token.length<32)return json({error:'Pilot-Link ungültig'},401);
 const {data:tester}=await admin.from('kc_dp_pilot_testers').select('*').eq('invite_token_hash',await sha256(token)).maybeSingle();if(!tester||tester.status==='revoked')return json({error:'Pilot-Link ist ungültig oder wurde deaktiviert'},401);
 const event=async(type:string,detail:any={})=>{await admin.from('kc_dp_pilot_events').insert({tester_id:tester.id,event_type:type,detail})};
 const advance=async(next:string,patch:any={})=>{if((rank[next]??0)>(rank[String(tester.status)]??0))await admin.from('kc_dp_pilot_testers').update({status:next,...patch,updated_at:new Date().toISOString()}).eq('id',tester.id)};
 let pub=Deno.env.get('KC_DP_VAPID_PUBLIC_KEY')||'',priv=Deno.env.get('KC_DP_VAPID_PRIVATE_KEY')||'',subject=Deno.env.get('KC_DP_VAPID_SUBJECT')||'mailto:admin@koecheclub-werne.de';if(!pub||!priv){const {data:r}=await admin.rpc('kc_dp_get_push_runtime_secrets');if(r){pub=String(r.vapidPublicKey||'');priv=String(r.vapidPrivateKey||'');subject=String(r.vapidSubject||subject)}}
 const action=String(body.action||'bootstrap');
 if(action==='bootstrap'){await advance('opened',{opened_at:tester.opened_at||new Date().toISOString()});await event('opened',{device:String(body.device||''),installed:!!body.installed});return json({ok:true,firstName:tester.first_name,expectedDevice:tester.expected_device,status:tester.status==='invited'?'opened':tester.status,vapidPublicKey:pub})}
 if(action==='installed'){await advance('installed',{installed_at:tester.installed_at||new Date().toISOString()});await event('installed',{device:String(body.device||'')});return json({ok:true,status:'installed'})}
 if(action==='subscribe'){const sub=body.subscription;if(!sub?.endpoint)return json({error:'Push-Subscription fehlt'},400);await admin.from('kc_dp_pilot_push_subscriptions').upsert({tester_id:tester.id,endpoint:String(sub.endpoint),subscription:sub,user_agent:String(body.userAgent||'').slice(0,500),device_reported:String(body.device||'').slice(0,30),active:true,updated_at:new Date().toISOString()},{onConflict:'tester_id,endpoint'});await advance('push_enabled',{push_enabled_at:tester.push_enabled_at||new Date().toISOString()});await event('push_enabled',{device:String(body.device||'')});return json({ok:true,status:'push_enabled'})}
 if(action==='test_received'){await advance('test_received',{test_received_at:tester.test_received_at||new Date().toISOString()});await event('test_push_opened',{device:String(body.device||'')});return json({ok:true,status:'test_received'})}
 const send=async(kind:'test'|'complete')=>{if(!pub||!priv)return json({error:'Push ist serverseitig nicht freigeschaltet'},503);webpush.setVapidDetails(subject,pub,priv);const {data:subs}=await admin.from('kc_dp_pilot_push_subscriptions').select('*').eq('tester_id',tester.id).eq('active',true);if(!subs?.length)return json({error:'Noch keine aktive Push-Registrierung vorhanden'},409);const ios=String(tester.expected_device)==='ios',remove=ios?'KC DP2 entfernen: App-Symbol lange drücken → App entfernen → Vom Home-Bildschirm entfernen. Mitteilungen können zusätzlich in Einstellungen → Mitteilungen → KC DP2 deaktiviert werden.':'KC DP2 entfernen: App-Symbol lange drücken → Deinstallieren bzw. App-Info → Deinstallieren. Benachrichtigungen können zusätzlich in App-Info deaktiviert werden.';const message=kind==='test'?{title:'KC DP2 – Pilot-Test',body:`Hallo ${tester.first_name}, diese Push-Nachricht bestätigt den KC-DP2-Pilottest. Bitte antippen.`,data:{route:'pilot',pilot:true,type:'test'}}:{title:'KC DP2 – Pilotphase beendet',body:`Der Entwickler bedankt sich bei ${tester.first_name} für deine Unterstützung. Vielen Dank für den Test!`,data:{route:'pilot_complete',pilot:true,type:'complete',uninstallHelp:remove}};let sent=0,failed=0;for(const row of subs){try{await webpush.sendNotification(row.subscription,JSON.stringify(message),{TTL:21600,urgency:'high'});sent++}catch(e){failed++;const code=Number((e as any).statusCode||0);if([404,410].includes(code))await admin.from('kc_dp_pilot_push_subscriptions').update({active:false,updated_at:new Date().toISOString()}).eq('id',row.id)}}if(kind==='complete'&&sent){await advance('completed',{completed_at:tester.completed_at||new Date().toISOString()});await admin.from('kc_dp_pilot_push_subscriptions').update({active:false,updated_at:new Date().toISOString()}).eq('tester_id',tester.id)}await event(kind==='test'?'test_push_sent':'completion_push_sent',{sent,failed});return json({ok:true,sent,failed,status:kind==='test'?'push_enabled':'completed'})};
 if(action==='send_test')return await send('test');if(action==='finish')return await send('complete');if(action==='heartbeat'){await event('heartbeat',{device:String(body.device||''),installed:!!body.installed,notification:String(body.notification||'')});return json({ok:true,status:tester.status})}return json({error:'Unbekannte Pilot-Aktion'},400);
});
