import { createClient } from 'npm:@supabase/supabase-js@2';
import webpush from 'npm:web-push@3.6.7';
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, apikey, content-type','Access-Control-Allow-Methods':'GET,POST,OPTIONS'};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,'Content-Type':'application/json'}});
const sha256=async(v:string)=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v)))).map(x=>x.toString(16).padStart(2,'0')).join('');
Deno.serve(async req=>{
 if(req.method==='OPTIONS')return new Response('ok',{headers:cors});
 const url=Deno.env.get('SUPABASE_URL')!,anon=Deno.env.get('SUPABASE_ANON_KEY')!,service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,pub=Deno.env.get('KC_DP_VAPID_PUBLIC_KEY')||'',priv=Deno.env.get('KC_DP_VAPID_PRIVATE_KEY')||'',subject=Deno.env.get('KC_DP_VAPID_SUBJECT')||'mailto:admin@koecheclub-werne.de';
 if(req.method==='GET')return json({ok:!!pub,vapidPublicKey:pub});
 const body=await req.json(),action=String(body.action||''),orgId=String(body.orgId||'KC_WERNE'),projectId=String(body.projectId||'KC_DP'),admin=createClient(url,service);
 if(action==='scheduled'){
  const {data:key}=await admin.from('kc_dp_cron_auth').select('secret_hash').eq('id','nightly_push').maybeSingle();if(!key||await sha256(String(body.cronSecret||''))!==key.secret_hash)return json({error:'Cron nicht berechtigt'},403);
  const {data:settings}=await admin.from('kc_dp_push_schedule_settings').select('*').eq('org_id',orgId).eq('project_id',projectId).eq('enabled',true).maybeSingle();if(!settings)return json({ok:true,skipped:'disabled'});
  const forced=body.force===true,forcedPeople=[...new Set((Array.isArray(body.personIds)?body.personIds:[]).map(String))];
  const parts=new Intl.DateTimeFormat('en-CA',{timeZone:settings.timezone||'Europe/Berlin',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date()),part=(t:string)=>parts.find(x=>x.type===t)?.value||'',today=`${part('year')}-${part('month')}-${part('day')}`,nowMin=Number(part('hour'))*60+Number(part('minute')),schedule=String(settings.local_time).slice(0,5).split(':').map(Number),due=schedule[0]*60+schedule[1];if(!forced&&(nowMin<due||nowMin>due+9))return json({ok:true,skipped:'not_due'});
  const tomorrow=new Date(`${today}T12:00:00Z`);tomorrow.setUTCDate(tomorrow.getUTCDate()+1);const serviceDate=forced&&/^\d{4}-\d{2}-\d{2}$/.test(String(body.serviceDate||''))?String(body.serviceDate):tomorrow.toISOString().slice(0,10);let previewQuery=admin.from('kc_dp_daily_push_preview').select('*').eq('org_id',orgId).eq('project_id',projectId).eq('service_date',serviceDate).eq('active',true);if(forced&&forcedPeople.length)previewQuery=previewQuery.in('person_id',forcedPeople);const {data:preview}=await previewQuery,rows=[...(preview||[])];if(!forced&&settings.recipient_scope==='all_active'){const existing=new Set(rows.map((x:any)=>x.person_id)),{data:members}=await admin.from('kc_dp_memberships').select('person_id').eq('org_id',orgId).eq('active',true);for(const m of members||[])if(m.person_id&&!existing.has(m.person_id))rows.push({person_id:m.person_id,shifts:[]})}if(!pub||!priv)return json({error:'VAPID fehlt'},503);webpush.setVapidDetails(subject,pub,priv);let sent=0,failed=0,skipped=0;
  for(const row of rows||[]){const {data:claimed}=await admin.from('kc_dp_daily_push_runs').insert({org_id:orgId,project_id:projectId,service_date:serviceDate,person_id:row.person_id}).select().maybeSingle();if(!claimed){skipped++;continue}const shifts=Array.isArray(row.shifts)?row.shifts:[],summary=shifts.map((s:any)=>`${s.start}–${s.end} Uhr${s.area?' · '+s.area:''}`).join(' / '),notificationId=`DAILY-${serviceDate}-${row.person_id}`,message={title:'KC DP2 – Ihr Dienst morgen',body:summary||'Bitte persönlichen Tagesplan öffnen.',data:{notificationId,route:'personal_plan',date:serviceDate,automatic:true}},{data:subs}=await admin.from('kc_dp_push_subscriptions').select('id,user_id,person_id,subscription').eq('org_id',orgId).eq('project_id',projectId).eq('person_id',row.person_id).eq('active',true);for(const sub of subs||[]){const base={org_id:orgId,project_id:projectId,notification_id:notificationId,subscription_id:sub.id,user_id:sub.user_id,person_id:sub.person_id,title:message.title};await admin.from('kc_dp_push_deliveries').upsert({...base,status:'queued'},{onConflict:'notification_id,subscription_id'});try{await webpush.sendNotification(sub.subscription,JSON.stringify(message));sent++;await admin.from('kc_dp_push_deliveries').update({status:'sent',sent_at:new Date().toISOString()}).eq('notification_id',notificationId).eq('subscription_id',sub.id)}catch(e){failed++;await admin.from('kc_dp_push_deliveries').update({status:'failed',failed_at:new Date().toISOString(),error_code:String((e as any).statusCode||'push_error')}).eq('notification_id',notificationId).eq('subscription_id',sub.id)}}await admin.from('kc_dp_daily_push_runs').update({notification_id:notificationId,status:failed?'completed_with_errors':'completed'}).eq('org_id',orgId).eq('project_id',projectId).eq('service_date',serviceDate).eq('person_id',row.person_id)}return json({ok:true,serviceDate,sent,failed,skipped});
 }
 if(action==='replacementDispatch'){
  const {data:key}=await admin.from('kc_dp_cron_auth').select('secret_hash').eq('id','nightly_push').maybeSingle();if(!key||await sha256(String(body.cronSecret||''))!==key.secret_hash)return json({error:'Systemversand nicht berechtigt'},403);const requestId=String(body.requestId||''),{data:r}=await admin.from('kc_dp_replacement_requests').select('id,service_date,start_time,end_time,area,invited_person_ids,status').eq('id',requestId).eq('org_id',orgId).eq('project_id',projectId).maybeSingle();if(!r||r.status!=='open')return json({error:'Offene Vertretungsanfrage nicht gefunden'},404);if(!pub||!priv)return json({error:'VAPID fehlt'},503);webpush.setVapidDetails(subject,pub,priv);const ids=r.invited_person_ids||[],notificationId=`REPLACEMENT-${r.id}`,message={title:'KC DP2 – Vertretung gesucht',body:`${String(r.service_date).split('-').reverse().join('.')} · ${String(r.start_time).slice(0,5)}–${String(r.end_time).slice(0,5)} Uhr · ${r.area}.`,data:{notificationId,route:'replacement',requestId:r.id,date:r.service_date}},{data:subs}=await admin.from('kc_dp_push_subscriptions').select('id,user_id,person_id,subscription').eq('org_id',orgId).eq('project_id',projectId).eq('active',true).in('person_id',ids);let sent=0,failed=0;for(const sub of subs||[]){const base={org_id:orgId,project_id:projectId,notification_id:notificationId,subscription_id:sub.id,user_id:sub.user_id,person_id:sub.person_id,title:message.title};await admin.from('kc_dp_push_deliveries').upsert({...base,status:'queued'},{onConflict:'notification_id,subscription_id'});try{await webpush.sendNotification(sub.subscription,JSON.stringify(message));sent++;await admin.from('kc_dp_push_deliveries').update({status:'sent',sent_at:new Date().toISOString()}).eq('notification_id',notificationId).eq('subscription_id',sub.id)}catch(e){failed++;await admin.from('kc_dp_push_deliveries').update({status:'failed',failed_at:new Date().toISOString(),error_code:String((e as any).statusCode||'push_error')}).eq('notification_id',notificationId).eq('subscription_id',sub.id)}}return json({ok:true,requestId,sent,failed});
 }
 const auth=req.headers.get('Authorization')||'',userClient=createClient(url,anon,{global:{headers:{Authorization:auth}}}),{data:{user}}=await userClient.auth.getUser();if(!user)return json({error:'Anmeldung erforderlich'},401);
 const {data:membership}=await admin.from('kc_dp_memberships').select('person_id,role,active').eq('org_id',orgId).eq('user_id',user.id).eq('active',true).maybeSingle();if(!membership)return json({error:'Keine aktive Mitgliedschaft'},403);
 if(action==='subscribe'){
  const sub=body.subscription;if(!sub?.endpoint)return json({error:'Subscription fehlt'},400);
  const {error}=await admin.from('kc_dp_push_subscriptions').upsert({org_id:orgId,project_id:projectId,user_id:user.id,person_id:membership.person_id,endpoint:sub.endpoint,subscription:sub,user_agent:String(body.userAgent||'').slice(0,500),active:true,updated_at:new Date().toISOString()},{onConflict:'org_id,project_id,user_id,endpoint'});return error?json({error:error.message},400):json({ok:true});
 }
 if(action==='unsubscribe'){await admin.from('kc_dp_push_subscriptions').update({active:false,updated_at:new Date().toISOString()}).eq('org_id',orgId).eq('project_id',projectId).eq('user_id',user.id).eq('endpoint',String(body.endpoint||''));return json({ok:true});}
 if(action==='acknowledge'){
  const notificationId=String(body.notificationId||'');if(!notificationId)return json({error:'Nachrichten-ID fehlt'},400);
  const {error}=await admin.from('kc_dp_push_deliveries').update({status:'opened',opened_at:new Date().toISOString()}).eq('org_id',orgId).eq('project_id',projectId).eq('notification_id',notificationId).eq('user_id',user.id);
  return error?json({error:error.message},400):json({ok:true,status:'opened'});
 }
 if(action==='status'){
  if(!['planner','duty_manager','admin'].includes(String(membership.role)))return json({error:'Keine Auswertungsberechtigung'},403);
  const {data,error}=await admin.from('kc_dp_push_deliveries').select('notification_id,person_id,status,title,created_at,sent_at,failed_at,opened_at,error_code').eq('org_id',orgId).eq('project_id',projectId).order('created_at',{ascending:false}).limit(100);
  return error?json({error:error.message},400):json({ok:true,deliveries:data||[]});
 }
 if(action==='scheduleSettings'){
  if(!['planner','duty_manager','admin'].includes(String(membership.role)))return json({error:'Keine Einstellungsberechtigung'},403);if(body.patch){const patch={enabled:body.patch.enabled!==false,local_time:String(body.patch.localTime||'20:00'),timezone:'Europe/Berlin',recipient_scope:body.patch.recipientScope==='all_active'?'all_active':'scheduled',updated_by:user.id,updated_at:new Date().toISOString()};const {error}=await admin.from('kc_dp_push_schedule_settings').upsert({org_id:orgId,project_id:projectId,...patch},{onConflict:'org_id,project_id'});if(error)return json({error:error.message},400)}const {data}=await admin.from('kc_dp_push_schedule_settings').select('*').eq('org_id',orgId).eq('project_id',projectId).maybeSingle();return json({ok:true,settings:data});
 }
 if(action==='publishPreview'){
  if(!['planner','duty_manager','admin'].includes(String(membership.role)))return json({error:'Keine Veröffentlichungsberechtigung'},403);const rows=Array.isArray(body.rows)?body.rows.slice(0,1000):[];for(const r of rows){await admin.from('kc_dp_daily_push_preview').upsert({org_id:orgId,project_id:projectId,service_date:r.date,person_id:String(r.personId),plan_version:Number(body.planVersion||0),shifts:Array.isArray(r.shifts)?r.shifts:[],active:true,updated_by:user.id,updated_at:new Date().toISOString()},{onConflict:'org_id,project_id,service_date,person_id'})}return json({ok:true,rows:rows.length});
 }
 if(action==='replacementCreate'){
  if(!['planner','duty_manager','admin'].includes(String(membership.role)))return json({error:'Keine Berechtigung für Vertretungsanfragen'},403);const ids=[...new Set((Array.isArray(body.personIds)?body.personIds:[]).map(String).filter(Boolean))].slice(0,100),date=String(body.date||''),start=String(body.start||''),end=String(body.end||''),area=String(body.area||'Hinten').slice(0,80),zone=String(body.zone||'back').slice(0,20);if(!ids.length||!/^\d{4}-\d{2}-\d{2}$/.test(date)||!/^\d{2}:\d{2}$/.test(start)||!/^\d{2}:\d{2}$/.test(end))return json({error:'Datum, Zeit oder Empfänger fehlen'},400);const expiresAt=new Date(`${date}T${start}:00+02:00`).toISOString(),{data,error}=await admin.from('kc_dp_replacement_requests').insert({org_id:orgId,project_id:projectId,service_date:date,start_time:start,end_time:end,area,zone,reason_category:String(body.reasonCategory||'personalausfall').slice(0,50),invited_person_ids:ids,created_by:user.id,expires_at:expiresAt}).select().single();return error?json({error:error.message},400):json({ok:true,request:data});
 }
 if(action==='replacementGet'){
  const id=String(body.requestId||''),{data,error}=await admin.from('kc_dp_replacement_requests').select('id,service_date,start_time,end_time,area,zone,status,assigned_person_id,invited_person_ids,expires_at').eq('id',id).eq('org_id',orgId).eq('project_id',projectId).maybeSingle();if(error||!data)return json({error:'Vertretungsanfrage nicht gefunden'},404);if(!['planner','duty_manager','admin'].includes(String(membership.role))&&!data.invited_person_ids?.includes(membership.person_id))return json({error:'Diese Anfrage ist nicht für Sie bestimmt'},403);return json({ok:true,request:data});
 }
 if(action==='replacementRespond'){
  const {data,error}=await admin.rpc('kc_dp_accept_replacement',{p_request_id:String(body.requestId||''),p_user_id:user.id,p_accept:body.accept===true});return error?json({error:error.message},409):json({ok:true,result:data});
 }
 if(action==='replacementAssignments'){
  if(!['planner','duty_manager','admin'].includes(String(membership.role)))return json({error:'Keine Planungsberechtigung'},403);const {data,error}=await admin.from('kc_dp_replacement_requests').select('id,service_date,start_time,end_time,area,zone,status,assigned_person_id,accepted_at,synced_at').eq('org_id',orgId).eq('project_id',projectId).eq('status','filled').is('synced_at',null).order('accepted_at');return error?json({error:error.message},400):json({ok:true,assignments:data||[]});
 }
 if(action==='replacementSynced'){
  if(!['planner','duty_manager','admin'].includes(String(membership.role)))return json({error:'Keine Planungsberechtigung'},403);const {error}=await admin.from('kc_dp_replacement_requests').update({synced_at:new Date().toISOString()}).eq('id',String(body.requestId||'')).eq('org_id',orgId).eq('project_id',projectId).eq('status','filled');return error?json({error:error.message},400):json({ok:true});
 }
 if(action==='send'){
  if(!['planner','duty_manager','admin'].includes(String(membership.role)))return json({error:'Keine Versandberechtigung'},403);if(!pub||!priv)return json({error:'VAPID noch nicht serverseitig konfiguriert'},503);webpush.setVapidDetails(subject,pub,priv);
  const ids=[...new Set((body.personIds||[]).map(String))],notificationId=String(body.payload?.data?.notificationId||crypto.randomUUID()),message={...(body.payload||{}),data:{...(body.payload?.data||{}),notificationId}},payload=JSON.stringify(message),{data:subs,error}=await admin.from('kc_dp_push_subscriptions').select('id,user_id,person_id,subscription').eq('org_id',orgId).eq('project_id',projectId).eq('active',true).in('person_id',ids);if(error)return json({error:error.message},400);let sent=0,failed=0;for(const row of subs||[]){const base={org_id:orgId,project_id:projectId,notification_id:notificationId,subscription_id:row.id,user_id:row.user_id,person_id:row.person_id,title:String(message.title||'').slice(0,200)};await admin.from('kc_dp_push_deliveries').upsert({...base,status:'queued'},{onConflict:'notification_id,subscription_id'});try{await webpush.sendNotification(row.subscription,payload);sent++;await admin.from('kc_dp_push_deliveries').update({status:'sent',sent_at:new Date().toISOString(),error_code:null}).eq('notification_id',notificationId).eq('subscription_id',row.id)}catch(e){failed++;const code=String(Number((e as {statusCode?:number}).statusCode)||'push_error');await admin.from('kc_dp_push_deliveries').update({status:'failed',failed_at:new Date().toISOString(),error_code:code}).eq('notification_id',notificationId).eq('subscription_id',row.id);if([404,410].includes(Number(code)))await admin.from('kc_dp_push_subscriptions').update({active:false}).eq('id',row.id)}}return json({ok:true,notificationId,sent,failed});
 }
 return json({error:'Unbekannte Aktion'},400);
});
