import { createClient } from 'npm:@supabase/supabase-js@2';
import * as XLSX from 'npm:xlsx@0.18.5';
import { decryptMailAttachment } from '../_shared/kc-dp-mail-crypto.ts';

const json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{'Content-Type':'application/json','Cache-Control':'no-store'}});
const clean=(v:any)=>String(v??'').replace(/\u00a0/g,' ').trim();
const norm=(v:any)=>clean(v).toLowerCase().replace(/\s+/g,' ');
const yes=(v:any)=>['ja','j','yes','y','1','true','x','✓'].includes(norm(v));
const field=(row:any,names:string[])=>{for(const [k,v] of Object.entries(row||{}))if(names.map(norm).includes(norm(k)))return v;return''};
function date(v:any){if(v instanceof Date&&!Number.isNaN(v.getTime()))return v.toISOString().slice(0,10);if(typeof v==='number'&&Number.isFinite(v))return new Date(Math.round((v-25569)*86400000)).toISOString().slice(0,10);const s=clean(v);if(/^\d{4}-\d{2}-\d{2}$/.test(s))return s;const m=s.match(/^(\d{1,2})[.\/-](\d{1,2})[.\/-](\d{2,4})$/);return m?`${m[3].length===2?'20'+m[3]:m[3]}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}`:''}
function time(v:any){if(typeof v==='number'&&Number.isFinite(v))return v>=0&&v<1?v*24:v>=0&&v<=24?v:null;const s=clean(v);const m=s.match(/^(\d{1,2}):(\d{2})$/);if(!m)return null;const h=Number(m[1]),mi=Number(m[2]);return h<=24&&mi<60?h+mi/60:null}
function parseRows(bytes:Uint8Array){const wb=XLSX.read(bytes,{type:'array',cellDates:true}),ws=wb.Sheets[wb.SheetNames[0]],matrix=XLSX.utils.sheet_to_json(ws,{header:1,raw:true,defval:''}) as any[][];const headersWanted=['datum','kann von','kann bis','v/h/b','wunsch von','wunsch bis','sperrzeit von','sperrzeit bis','sperrtag','nur wenn nötig','bemerkung'];const hi=matrix.findIndex(r=>{const n=r.map(norm);return n.includes('datum')&&headersWanted.filter(h=>n.includes(h)).length>=4});if(hi<0)throw new Error('Keine KC-DP2-Wunschmatrix erkannt');const headers=matrix[hi].map(clean),rows:any[]=[];for(let i=hi+1;i<matrix.length;i++){const vals=matrix[i];if(!vals.some(x=>clean(x)))continue;const o:any={__row:i+1};headers.forEach((h,j)=>{if(h)o[h]=vals[j]});rows.push(o)}return rows}
function validate(rows:any[]){const entries:any[]=[],issues:any[]=[];for(const r of rows){const d=date(field(r,['Datum']));if(!d){issues.push({row:r.__row,level:'error',text:'Datum fehlt oder ist nicht lesbar.'});continue}const z=clean(field(r,['V/H/B','VHB'])).toUpperCase()||'B';if(!['V','H','B'].includes(z)){issues.push({row:r.__row,level:'error',text:'V/H/B erlaubt ausschließlich V, H oder B.'});continue}const remark=clean(field(r,['Bemerkung','Kommentar'])),blocked=yes(field(r,['Sperrtag'])),reserve=yes(field(r,['Nur wenn nötig','Reserve']));const cv=time(field(r,['Kann von'])),cb=time(field(r,['Kann bis'])),wv=time(field(r,['Wunsch von'])),wb=time(field(r,['Wunsch bis'])),sv=time(field(r,['Sperrzeit von'])),sb=time(field(r,['Sperrzeit bis']));if(blocked){entries.push({date:d,start:0,end:24,wishType:'unavailable',wishZone:'B',comment:remark||'Sperrtag'});continue}if((cv==null)!=(cb==null))issues.push({row:r.__row,level:'error',text:'Kann von/bis unvollständig.'});else if(cv!=null&&cb!=null){if(cb<=cv)issues.push({row:r.__row,level:'error',text:'Kann bis muss nach Kann von liegen.'});else entries.push({date:d,start:cv,end:cb,wishType:reserve?'if_needed':'available',wishZone:z,comment:remark})}if((wv==null)!=(wb==null))issues.push({row:r.__row,level:'error',text:'Wunsch von/bis unvollständig.'});else if(wv!=null&&wb!=null){if(cv==null||cb==null||wv<cv||wb>cb||wb<=wv||reserve)issues.push({row:r.__row,level:'error',text:'Wunschzeit ist widersprüchlich oder liegt nicht vollständig in der Kann-Zeit.'});else entries.push({date:d,start:wv,end:wb,wishType:'preferred',wishZone:z,comment:remark})}if((sv==null)!=(sb==null))issues.push({row:r.__row,level:'error',text:'Sperrzeit von/bis unvollständig.'});else if(sv!=null&&sb!=null){if(sb<=sv)issues.push({row:r.__row,level:'error',text:'Sperrzeit bis muss nach Sperrzeit von liegen.'});else entries.push({date:d,start:sv,end:sb,wishType:'unavailable',wishZone:'B',comment:remark})}}
return{entries,issues,valid:!issues.some(x=>x.level==='error')}}

Deno.serve(async(req)=>{if(req.method!=='POST')return json({error:'POST erforderlich'},405);const url=Deno.env.get('SUPABASE_URL')||'',service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'',admin=createClient(url,service,{auth:{persistSession:false,autoRefreshToken:false}});let body:any={};try{body=await req.json()}catch{return json({error:'Ungültiges JSON'},400)}const attachmentId=String(body.attachmentId||'');if(!attachmentId)return json({error:'attachmentId fehlt'},400);
const {data:a,error:aErr}=await admin.from('kc_dp_inbox_attachments').select('id,message_id,file_name,detected_kind,storage_path,encryption_iv,plaintext_sha256,content_status').eq('id',attachmentId).maybeSingle();if(aErr||!a)return json({error:'Anhang nicht gefunden'},404);if(!['xlsx','xls','csv'].includes(a.detected_kind))return json({error:'Dieser Processor verarbeitet nur Excel/CSV'},400);if(a.content_status!=='encrypted'||!a.storage_path||!a.encryption_iv)return json({error:'Anhang liegt nicht verschlüsselt verarbeitbar vor'},409);
const {data:m}=await admin.from('kc_dp_inbox_messages').select('id,person_id,person_match_confidence,document_id,from_address').eq('id',a.message_id).maybeSingle();let personId=m?.person_id||null,confidence=Number(m?.person_match_confidence||0);if(!personId&&m?.from_address){const {data:mm}=await admin.from('kc_dp_memberships').select('person_id,email').eq('org_id','KC_WERNE').eq('active',true).ilike('email',String(m.from_address)).maybeSingle();if(mm?.person_id){personId=mm.person_id;confidence=.95;await admin.from('kc_dp_inbox_messages').update({person_id:personId,person_match_method:'sender',person_match_confidence:confidence}).eq('id',m.id)}}
const {data:blob,error:bErr}=await admin.storage.from('kc-dp-mail-quarantine').download(a.storage_path);if(bErr||!blob)return json({error:'Verschlüsselter Anhang nicht abrufbar'},500);const cipher=new Uint8Array(await blob.arrayBuffer()),aad=`KC_WERNE|KC_DP|${a.message_id}|${a.file_name}|${a.plaintext_sha256}`,plain=await decryptMailAttachment(cipher,a.encryption_iv,aad);let parsed:any;try{parsed=validate(parseRows(plain))}catch(e){parsed={entries:[],issues:[{row:0,level:'error',text:(e as Error).message}],valid:false}}
const {data:phase}=await admin.from('kc_dp_wish_phase_settings').select('status').eq('org_id','KC_WERNE').eq('project_id','KC_DP').maybeSingle(),wishOpen=phase?.status==='open';const auto=!!personId&&confidence>=.98&&!!m?.document_id&&wishOpen&&parsed.valid&&parsed.entries.length>0;const status=auto?'ready':'review';const {data:job,error:jErr}=await admin.from('kc_dp_import_jobs').insert({org_id:'KC_WERNE',project_id:'KC_DP',message_id:a.message_id,attachment_id:a.id,person_id:personId,document_id:m?.document_id||null,source_kind:'email_excel',status,confidence,auto_apply_eligible:auto,wish_phase_open:wishOpen,detected_rows:parsed.entries.length,valid_rows:parsed.valid?parsed.entries.length:0,error_rows:parsed.issues.filter((x:any)=>x.level==='error').length,normalized_payload:{entries:parsed.entries},issues:parsed.issues}).select().single();if(jErr)return json({error:jErr.message},400);await admin.from('kc_dp_inbox_attachments').update({parse_status:parsed.valid?(auto?'parsed':'review'):'invalid'}).eq('id',a.id);await admin.from('kc_dp_inbox_messages').update({status:auto?'processing':'review'}).eq('id',a.message_id);return json({ok:true,jobId:job.id,status,autoApplyEligible:auto,personId,confidence,wishPhaseOpen:wishOpen,entries:parsed.entries.length,issues:parsed.issues});});
