create table if not exists public.kc_dp_wish_phase_settings (
  org_id text not null,
  project_id text not null,
  deadline_date date,
  close_at timestamptz,
  timezone text not null default 'Europe/Berlin',
  reminder_days integer[] not null default array[3,1],
  push_enabled boolean not null default true,
  email_enabled boolean not null default true,
  status text not null default 'open' check (status in ('open','closed')),
  closed_at timestamptz,
  closed_by uuid,
  updated_by uuid,
  updated_at timestamptz not null default now(),
  primary key (org_id, project_id)
);

create table if not exists public.kc_dp_wish_phase_notification_runs (
  id bigint generated by default as identity primary key,
  org_id text not null,
  project_id text not null,
  event_key text not null,
  event_type text not null check (event_type in ('reminder','closed')),
  deadline_date date,
  created_at timestamptz not null default now(),
  push_sent integer not null default 0,
  push_failed integer not null default 0,
  email_sent integer not null default 0,
  email_failed integer not null default 0,
  detail jsonb not null default '{}'::jsonb,
  unique (org_id, project_id, event_key)
);

alter table public.kc_dp_wish_phase_settings enable row level security;
alter table public.kc_dp_wish_phase_notification_runs enable row level security;
revoke all on public.kc_dp_wish_phase_settings from anon, authenticated;
revoke all on public.kc_dp_wish_phase_notification_runs from anon, authenticated;
grant all on public.kc_dp_wish_phase_settings to service_role;
grant all on public.kc_dp_wish_phase_notification_runs to service_role;
grant usage, select on sequence public.kc_dp_wish_phase_notification_runs_id_seq to service_role;

comment on table public.kc_dp_wish_phase_settings is 'KC DP2 server-side Wunschphase deadline, automatic closing and notification configuration.';
comment on table public.kc_dp_wish_phase_notification_runs is 'Idempotent audit log for KC DP2 Wunschphase reminder and closure notifications.';
