create table if not exists public.kc_dp_pilot_testers (
  id uuid primary key default gen_random_uuid(),
  org_id text not null default 'KC_WERNE',
  project_id text not null default 'KC_DP',
  person_id text not null unique,
  first_name text not null,
  phone_e164 text,
  expected_device text not null check (expected_device in ('ios','android','other')),
  invite_token_hash text not null unique,
  status text not null default 'invited' check (status in ('invited','opened','installed','push_enabled','test_received','completed','revoked')),
  opened_at timestamptz,
  installed_at timestamptz,
  push_enabled_at timestamptz,
  test_received_at timestamptz,
  completed_at timestamptz,
  revoked_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.kc_dp_pilot_push_subscriptions (
  id uuid primary key default gen_random_uuid(),
  tester_id uuid not null references public.kc_dp_pilot_testers(id) on delete cascade,
  endpoint text not null,
  subscription jsonb not null,
  user_agent text,
  device_reported text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (tester_id, endpoint)
);

create table if not exists public.kc_dp_pilot_events (
  id bigint generated by default as identity primary key,
  tester_id uuid not null references public.kc_dp_pilot_testers(id) on delete cascade,
  event_type text not null,
  detail jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.kc_dp_pilot_testers enable row level security;
alter table public.kc_dp_pilot_push_subscriptions enable row level security;
alter table public.kc_dp_pilot_events enable row level security;

revoke all on public.kc_dp_pilot_testers from anon, authenticated;
revoke all on public.kc_dp_pilot_push_subscriptions from anon, authenticated;
revoke all on public.kc_dp_pilot_events from anon, authenticated;

create index if not exists kc_dp_pilot_events_tester_created_idx
  on public.kc_dp_pilot_events(tester_id, created_at desc);
create index if not exists kc_dp_pilot_sub_active_idx
  on public.kc_dp_pilot_push_subscriptions(tester_id, active);

comment on table public.kc_dp_pilot_testers is
  'External KC DP2 pilot testers; intentionally separate from club memberships and scheduling.';
